# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main


pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'production'
  system.debug: 'true'

steps:
- script:
    npm install
    npm run build --omit=dev
  displayName: 'Build angular app'
- task: PublishBuildArtifacts@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/dist'
    ArtifactName: 'angular-app'
  displayName: 'Publist Build Artifacts'
